/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entities.UnmannedSpaceShip;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;

/**
 *
 * @author saymo
 */
public class Unmannedss extends javax.swing.JFrame {

    /**
     * Creates new form Shuttless
     */
    public Unmannedss() {
        newUnmannedSS = new UnmannedSpaceShip("blue-gray", 700);
        newUnmannedSS.Launch();
        count = 1;
        initComponents();
        lblTime.setVisible(false);
        txtTime.setVisible(false);
        lblAtm.setVisible(false);
        txtAtm.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtHeight = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSpeed = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblTime = new javax.swing.JLabel();
        btnLaunch = new javax.swing.JButton();
        txtTime = new javax.swing.JLabel();
        lblAtm = new javax.swing.JLabel();
        txtAtm = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("x");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 30));

        jPanel1.setBackground(new java.awt.Color(108, 138, 168));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Launch stats");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, -1));

        txtHeight.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        txtHeight.setForeground(new java.awt.Color(255, 255, 255));
        txtHeight.setText("0km");
        jPanel1.add(txtHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 120, 10));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Current height");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 20));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Current speed");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, 20));

        txtSpeed.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        txtSpeed.setForeground(new java.awt.Color(255, 255, 255));
        txtSpeed.setText("0km/h");
        jPanel1.add(txtSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 100, 20));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 87, 120, -1));

        lblTime.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 14)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("Current time:");
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        btnLaunch.setBackground(new java.awt.Color(197, 219, 248));
        btnLaunch.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        btnLaunch.setText("Launch!");
        btnLaunch.setToolTipText("");
        btnLaunch.setBorder(null);
        btnLaunch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaunch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaunchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaunchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaunchMouseExited(evt);
            }
        });
        jPanel1.add(btnLaunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 70, 30));

        txtTime.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 14)); // NOI18N
        txtTime.setForeground(new java.awt.Color(255, 255, 255));
        txtTime.setText("0min");
        jPanel1.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        lblAtm.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 14)); // NOI18N
        lblAtm.setForeground(new java.awt.Color(255, 255, 255));
        lblAtm.setText("Current atmosphere");
        jPanel1.add(lblAtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 140, -1));

        txtAtm.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 14)); // NOI18N
        txtAtm.setForeground(new java.awt.Color(255, 255, 255));
        txtAtm.setText("Troposphere");
        jPanel1.add(txtAtm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 160, 370));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/satellite.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg1.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        System.exit(0);
        evt.consume();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(Color.red);
        jLabel6.setForeground(Color.white);
        evt.consume();
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(Color.white);
        jLabel6.setForeground(Color.black);
        evt.consume();
    }//GEN-LAST:event_jPanel3MouseExited

    private void btnLaunchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaunchMouseClicked
        btnLaunch.setVisible(false);
        Launch();
    }//GEN-LAST:event_btnLaunchMouseClicked

    private void btnLaunchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaunchMouseEntered
        btnLaunch.setBackground(new java.awt.Color(137, 178, 220));
        evt.consume();
    }//GEN-LAST:event_btnLaunchMouseEntered

    private void btnLaunchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaunchMouseExited
        btnLaunch.setBackground(new java.awt.Color(108, 138, 168));
        evt.consume();
    }//GEN-LAST:event_btnLaunchMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnLaunch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAtm;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel txtAtm;
    private javax.swing.JLabel txtHeight;
    private javax.swing.JLabel txtSpeed;
    private javax.swing.JLabel txtTime;
    // End of variables declaration//GEN-END:variables
    private final UnmannedSpaceShip newUnmannedSS;
    int count;

    private void Launch() {
        SwingWorker<Void, Integer> worker = new SwingWorker<Void, Integer>() {
            @Override
            protected Void doInBackground() throws Exception {
                lblTime.setVisible(true);
                txtTime.setVisible(true);
                lblAtm.setVisible(true);
                txtAtm.setVisible(true);
                try {
                    Thread.sleep(2000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Unmannedss.class.getName()).log(Level.SEVERE, null, ex);
                }
                while (newUnmannedSS.getHeight() < 10000.00) {
                    if (newUnmannedSS.getHeight() <= 200) {
                        txtAtm.setText("Troposphere");                        
                    } else if(newUnmannedSS.getHeight() <= 500){
                        txtAtm.setText("Stratosphere");
                        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg2.jpg")));
                    } else if(newUnmannedSS.getHeight() <= 800){
                        txtAtm.setText("Mesosphere");
                        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg3.jpg")));
                    } else if(newUnmannedSS.getHeight() <= 1200){
                        txtAtm.setText("Thermosphere");
                        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg4.png")));
                    } else {
                        txtAtm.setText("Exosphere");
                        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg5.jpg")));
                    }
                    // Simulates work                    
                    txtHeight.setText(String.valueOf(newUnmannedSS.getHeight()) + "km");
                    txtSpeed.setText(String.valueOf(newUnmannedSS.getVelocity()) + "km/h");
                    txtTime.setText(String.valueOf(count * 4 + count) + "min");
                    newUnmannedSS.setHeight(newUnmannedSS.getHeight() / count);
                    count++;
                    Thread.sleep(2000);
                }                
                newUnmannedSS.stopLaunch();
                txtSpeed.setText(String.valueOf(newUnmannedSS.getVelocity()));
                txtAtm.setText("Outer space");
                return null;
            }
//            @Override
//            protected void process(List<Integer> chunks) {
//                progressTextField.setText(chunks.get(chunks.size() - 1).toString());
//            }
//
//            @Override
//            protected void done() {
//                progressTextField.setText("Done");
//            }
        };
        worker.execute();
    }
}
